export const MenuItem = {
  AddFolder: 'addFolder',
  AddPage: 'addPage',
  AddSeparator: 'addSeparator',
  Copy: 'copy',
  Cut: 'cut',
  Delete: 'del',
  Edit: 'edit',
  OpenAll: 'openAll',
  OpenAllInIncognitoWindow: 'openAllInI',
  OpenAllInNewWindow: 'openAllInN',
  OpenInBackgroundTab: 'openInB',
  OpenInIncognitoWindow: 'openInI',
  OpenInNewWindow: 'openInN',
  Paste: 'paste',
  Rename: 'rename',
  SortByName: 'sortByName',
} as const
