import * as CST from '../../../../constants'

export default [
  {
    children: [
      {
        iconUrl: 'http://ma.kz/vawujij',
        id: '3284',
        isRoot: true,
        isSimulated: false,
        isUnmodifiable: true,
        parentId: '5594',
        storageIndex: 7839,
        title: 'ahobaom',
        type: CST.BOOKMARK_TYPES.BOOKMARK,
        url: 'http://bigeha.pa/bejozkal',
      },
      {
        iconUrl: 'http://va.my/aso',
        id: '9551',
        isRoot: true,
        isSimulated: false,
        isUnmodifiable: true,
        parentId: '5517',
        storageIndex: 2338,
        title: 'gu',
        type: CST.BOOKMARK_TYPES.BOOKMARK,
        url: 'http://iza.gs/ge',
      },
      {
        iconUrl: 'http://remahfur.ec/wek',
        id: '8165',
        isRoot: false,
        isSimulated: false,
        isUnmodifiable: true,
        parentId: '5893',
        storageIndex: 5021,
        title: 'ilo',
        type: CST.BOOKMARK_TYPES.BOOKMARK,
        url: 'http://jabo.vu/mabheku',
      },
      {
        iconUrl: 'http://buk.az/kusa',
        id: '9557',
        isRoot: true,
        isSimulated: false,
        isUnmodifiable: true,
        parentId: '2384',
        storageIndex: 8077,
        title: 'ji',
        type: CST.BOOKMARK_TYPES.BOOKMARK,
        url: 'http://gepfim.md/udojigu',
      },
      {
        iconUrl: 'http://sumjueja.om/ewnobti',
        id: '9548',
        isRoot: true,
        isSimulated: false,
        isUnmodifiable: true,
        parentId: '3059',
        storageIndex: 8012,
        title: 'juetpoh',
        type: CST.BOOKMARK_TYPES.BOOKMARK,
        url: 'http://keil.ye/oku',
      },
      {
        iconUrl: 'http://uworodim.tc/dud',
        id: '2298',
        isRoot: false,
        isSimulated: false,
        isUnmodifiable: true,
        parentId: '4531',
        storageIndex: 8972,
        title: 'mipfo',
        type: CST.BOOKMARK_TYPES.BOOKMARK,
        url: 'http://ra.my/jozureb',
      },
      {
        iconUrl: 'http://pedet.se/vibjuwdik',
        id: '1217',
        isRoot: false,
        isSimulated: false,
        isUnmodifiable: false,
        parentId: '2530',
        storageIndex: 620,
        title: 'mombukfes',
        type: CST.BOOKMARK_TYPES.BOOKMARK,
        url: 'http://keil.gm/wokuj',
      },
    ],
    parent: {
      iconUrl: '',
      id: 'SEARCH_RESULT_ID',
      isRoot: false,
      isSimulated: true,
      isUnmodifiable: true,
      parentId: '',
      storageIndex: -1,
      title: '',
      type: CST.BOOKMARK_TYPES.FOLDER,
      url: '',
    },
  },
]
