// flow-typed signature: bf9d714be43a7d1a0c877fe459efb753
// flow-typed version: <<STUB>>/babel-preset-foray1010_v^8.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-foray1010'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-foray1010' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-foray1010/lib/getEnv' {
  declare module.exports: any;
}

declare module 'babel-preset-foray1010/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-foray1010/lib/getEnv.js' {
  declare module.exports: $Exports<'babel-preset-foray1010/lib/getEnv'>;
}
declare module 'babel-preset-foray1010/react.js' {
  declare module.exports: $Exports<'babel-preset-foray1010/react'>;
}
