// flow-typed signature: 599d0ad0e063e5a04678ebdd118cd34b
// flow-typed version: <<STUB>>/chrome-manifest-loader_v0.1.2/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrome-manifest-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrome-manifest-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrome-manifest-loader/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrome-manifest-loader/src/index.js' {
  declare module.exports: $Exports<'chrome-manifest-loader/src/index'>;
}
