// flow-typed signature: bc617b27d209c2d19547ca7c3087356e
// flow-typed version: <<STUB>>/duplicate-package-checker-webpack-plugin_v3.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'duplicate-package-checker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'duplicate-package-checker-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'duplicate-package-checker-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'duplicate-package-checker-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'duplicate-package-checker-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'duplicate-package-checker-webpack-plugin/lib/index'>;
}
declare module 'duplicate-package-checker-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'duplicate-package-checker-webpack-plugin/src/index'>;
}
