// flow-typed signature: 9af6739165098222ab64d23dbe352687
// flow-typed version: <<STUB>>/eslint-config-foray1010_v6.19.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-foray1010'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-foray1010' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-foray1010/babel-node' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/lib/extendsConfig' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/react' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/babel' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/base' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/es-modules' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/flow' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/frontend' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/plain-nodejs' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/ramda' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/typescript' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/rules/unit-test' {
  declare module.exports: any;
}

declare module 'eslint-config-foray1010/typescript' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-foray1010/babel-node.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/babel-node'>;
}
declare module 'eslint-config-foray1010/index' {
  declare module.exports: $Exports<'eslint-config-foray1010'>;
}
declare module 'eslint-config-foray1010/index.js' {
  declare module.exports: $Exports<'eslint-config-foray1010'>;
}
declare module 'eslint-config-foray1010/lib/extendsConfig.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/lib/extendsConfig'>;
}
declare module 'eslint-config-foray1010/react.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/react'>;
}
declare module 'eslint-config-foray1010/rules/babel.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/babel'>;
}
declare module 'eslint-config-foray1010/rules/base.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/base'>;
}
declare module 'eslint-config-foray1010/rules/es-modules.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/es-modules'>;
}
declare module 'eslint-config-foray1010/rules/flow.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/flow'>;
}
declare module 'eslint-config-foray1010/rules/frontend.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/frontend'>;
}
declare module 'eslint-config-foray1010/rules/plain-nodejs.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/plain-nodejs'>;
}
declare module 'eslint-config-foray1010/rules/ramda.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/ramda'>;
}
declare module 'eslint-config-foray1010/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/react'>;
}
declare module 'eslint-config-foray1010/rules/typescript.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/typescript'>;
}
declare module 'eslint-config-foray1010/rules/unit-test.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/rules/unit-test'>;
}
declare module 'eslint-config-foray1010/typescript.js' {
  declare module.exports: $Exports<'eslint-config-foray1010/typescript'>;
}
