// flow-typed signature: 98f09b84e3fe2f3edb20aa118b34c16c
// flow-typed version: <<STUB>>/ignore-sync_v^1.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ignore-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ignore-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ignore-sync/src/app' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/bin' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/cleanupIgnoreSyncFile' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/decodeIgnoreSyncFile' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/generateIgnoreFile' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/getIgnoreSyncFiles' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/isIgnoreSyncFile' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/readFileFromProjectRoot' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/utils/github' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/utils/ramdaHelper' {
  declare module.exports: any;
}

declare module 'ignore-sync/src/writeIgnoreFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ignore-sync/src/app.js' {
  declare module.exports: $Exports<'ignore-sync/src/app'>;
}
declare module 'ignore-sync/src/bin.js' {
  declare module.exports: $Exports<'ignore-sync/src/bin'>;
}
declare module 'ignore-sync/src/cleanupIgnoreSyncFile.js' {
  declare module.exports: $Exports<'ignore-sync/src/cleanupIgnoreSyncFile'>;
}
declare module 'ignore-sync/src/decodeIgnoreSyncFile.js' {
  declare module.exports: $Exports<'ignore-sync/src/decodeIgnoreSyncFile'>;
}
declare module 'ignore-sync/src/generateIgnoreFile.js' {
  declare module.exports: $Exports<'ignore-sync/src/generateIgnoreFile'>;
}
declare module 'ignore-sync/src/getIgnoreSyncFiles.js' {
  declare module.exports: $Exports<'ignore-sync/src/getIgnoreSyncFiles'>;
}
declare module 'ignore-sync/src/isIgnoreSyncFile.js' {
  declare module.exports: $Exports<'ignore-sync/src/isIgnoreSyncFile'>;
}
declare module 'ignore-sync/src/readFileFromProjectRoot.js' {
  declare module.exports: $Exports<'ignore-sync/src/readFileFromProjectRoot'>;
}
declare module 'ignore-sync/src/utils/github.js' {
  declare module.exports: $Exports<'ignore-sync/src/utils/github'>;
}
declare module 'ignore-sync/src/utils/ramdaHelper.js' {
  declare module.exports: $Exports<'ignore-sync/src/utils/ramdaHelper'>;
}
declare module 'ignore-sync/src/writeIgnoreFile.js' {
  declare module.exports: $Exports<'ignore-sync/src/writeIgnoreFile'>;
}
