// flow-typed signature: aae95772e1284e363225b5405e4c6aed
// flow-typed version: <<STUB>>/image-process-loader_v^1.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-process-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-process-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'image-process-loader/src/index' {
  declare module.exports: any;
}

declare module 'image-process-loader/src/lib/asyncWrapper' {
  declare module.exports: any;
}

declare module 'image-process-loader/src/lib/processImage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'image-process-loader/src/index.js' {
  declare module.exports: $Exports<'image-process-loader/src/index'>;
}
declare module 'image-process-loader/src/lib/asyncWrapper.js' {
  declare module.exports: $Exports<'image-process-loader/src/lib/asyncWrapper'>;
}
declare module 'image-process-loader/src/lib/processImage.js' {
  declare module.exports: $Exports<'image-process-loader/src/lib/processImage'>;
}
