// flow-typed signature: 8d201dda48eb958dc8e100e29d43dae0
// flow-typed version: <<STUB>>/import-sort-parser-babylon_v5.2.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'import-sort-parser-babylon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'import-sort-parser-babylon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'import-sort-parser-babylon/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'import-sort-parser-babylon/lib/index.js' {
  declare module.exports: $Exports<'import-sort-parser-babylon/lib/index'>;
}
