// flow-typed signature: 174e426590af6810996919993bf73649
// flow-typed version: <<STUB>>/markdownlint-cli_v^0.13.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdownlint-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdownlint-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdownlint-cli/markdownlint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdownlint-cli/markdownlint.js' {
  declare module.exports: $Exports<'markdownlint-cli/markdownlint'>;
}
