// flow-typed signature: 57a1d43011037119b1cd896bf823babd
// flow-typed version: <<STUB>>/open-color_v1.6.3/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open-color' {
  declare module.exports: any;
}
