// flow-typed signature: 9fb9524c2a34014d790a693c3363b81e
// flow-typed version: <<STUB>>/open-color_v^1.4.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'open-color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'open-color' {
  declare module.exports: any;
}
