// flow-typed signature: 042a9df0d0ae3b4aad15785feb4f37f8
// flow-typed version: <<STUB>>/postcss-url_v8.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-url/src/index' {
  declare module.exports: any;
}

declare module 'postcss-url/src/lib/decl-processor' {
  declare module.exports: any;
}

declare module 'postcss-url/src/lib/encode' {
  declare module.exports: any;
}

declare module 'postcss-url/src/lib/get-file' {
  declare module.exports: any;
}

declare module 'postcss-url/src/lib/hash' {
  declare module.exports: any;
}

declare module 'postcss-url/src/lib/match-options' {
  declare module.exports: any;
}

declare module 'postcss-url/src/lib/paths' {
  declare module.exports: any;
}

declare module 'postcss-url/src/type/copy' {
  declare module.exports: any;
}

declare module 'postcss-url/src/type/custom' {
  declare module.exports: any;
}

declare module 'postcss-url/src/type/inline' {
  declare module.exports: any;
}

declare module 'postcss-url/src/type/rebase' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-url/src/index.js' {
  declare module.exports: $Exports<'postcss-url/src/index'>;
}
declare module 'postcss-url/src/lib/decl-processor.js' {
  declare module.exports: $Exports<'postcss-url/src/lib/decl-processor'>;
}
declare module 'postcss-url/src/lib/encode.js' {
  declare module.exports: $Exports<'postcss-url/src/lib/encode'>;
}
declare module 'postcss-url/src/lib/get-file.js' {
  declare module.exports: $Exports<'postcss-url/src/lib/get-file'>;
}
declare module 'postcss-url/src/lib/hash.js' {
  declare module.exports: $Exports<'postcss-url/src/lib/hash'>;
}
declare module 'postcss-url/src/lib/match-options.js' {
  declare module.exports: $Exports<'postcss-url/src/lib/match-options'>;
}
declare module 'postcss-url/src/lib/paths.js' {
  declare module.exports: $Exports<'postcss-url/src/lib/paths'>;
}
declare module 'postcss-url/src/type/copy.js' {
  declare module.exports: $Exports<'postcss-url/src/type/copy'>;
}
declare module 'postcss-url/src/type/custom.js' {
  declare module.exports: $Exports<'postcss-url/src/type/custom'>;
}
declare module 'postcss-url/src/type/inline.js' {
  declare module.exports: $Exports<'postcss-url/src/type/inline'>;
}
declare module 'postcss-url/src/type/rebase.js' {
  declare module.exports: $Exports<'postcss-url/src/type/rebase'>;
}
