// flow-typed signature: 04e3addf0169789193c952e209a80baa
// flow-typed version: <<STUB>>/react-measure_v^2.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-measure'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-measure' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-measure/dist/react-measure' {
  declare module.exports: any;
}

declare module 'react-measure/dist/react-measure.min' {
  declare module.exports: any;
}

declare module 'react-measure/lib/get-content-rect' {
  declare module.exports: any;
}

declare module 'react-measure/lib/get-types' {
  declare module.exports: any;
}

declare module 'react-measure/lib/Measure' {
  declare module.exports: any;
}

declare module 'react-measure/lib/react-measure' {
  declare module.exports: any;
}

declare module 'react-measure/lib/with-content-rect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-measure/dist/react-measure.js' {
  declare module.exports: $Exports<'react-measure/dist/react-measure'>;
}
declare module 'react-measure/dist/react-measure.min.js' {
  declare module.exports: $Exports<'react-measure/dist/react-measure.min'>;
}
declare module 'react-measure/lib/get-content-rect.js' {
  declare module.exports: $Exports<'react-measure/lib/get-content-rect'>;
}
declare module 'react-measure/lib/get-types.js' {
  declare module.exports: $Exports<'react-measure/lib/get-types'>;
}
declare module 'react-measure/lib/Measure.js' {
  declare module.exports: $Exports<'react-measure/lib/Measure'>;
}
declare module 'react-measure/lib/react-measure.js' {
  declare module.exports: $Exports<'react-measure/lib/react-measure'>;
}
declare module 'react-measure/lib/with-content-rect.js' {
  declare module.exports: $Exports<'react-measure/lib/with-content-rect'>;
}
