// flow-typed signature: 35922f0a72c604dc1ff9987d73116931
// flow-typed version: <<STUB>>/stylelint-config-foray1010_v^4.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-foray1010'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-foray1010' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-foray1010/index' {
  declare module.exports: $Exports<'stylelint-config-foray1010'>;
}
declare module 'stylelint-config-foray1010/index.js' {
  declare module.exports: $Exports<'stylelint-config-foray1010'>;
}
