// flow-typed signature: da9fb3d8136c70746a609495dd824f30
// flow-typed version: <<STUB>>/transifex_v^1.4.4/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transifex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transifex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transifex/bin/index' {
  declare module.exports: any;
}

declare module 'transifex/tests/good-api-test' {
  declare module.exports: any;
}

declare module 'transifex/transifex' {
  declare module.exports: any;
}

declare module 'transifex/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transifex/bin/index.js' {
  declare module.exports: $Exports<'transifex/bin/index'>;
}
declare module 'transifex/tests/good-api-test.js' {
  declare module.exports: $Exports<'transifex/tests/good-api-test'>;
}
declare module 'transifex/transifex.js' {
  declare module.exports: $Exports<'transifex/transifex'>;
}
declare module 'transifex/url.js' {
  declare module.exports: $Exports<'transifex/url'>;
}
