// flow-typed signature: 6857d24440e6cfd4dbb527051f87f549
// flow-typed version: <<STUB>>/typeface-archivo-narrow_v0.0.54/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-archivo-narrow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-archivo-narrow' {
  declare module.exports: any;
}
