// flow-typed signature: 5f7f552916866960f03bbdb803fe8516
// flow-typed version: <<STUB>>/webextension-polyfill_v0.4.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webextension-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webextension-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webextension-polyfill/dist/browser-polyfill' {
  declare module.exports: any;
}

declare module 'webextension-polyfill/dist/browser-polyfill.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webextension-polyfill/dist/browser-polyfill.js' {
  declare module.exports: $Exports<'webextension-polyfill/dist/browser-polyfill'>;
}
declare module 'webextension-polyfill/dist/browser-polyfill.min.js' {
  declare module.exports: $Exports<'webextension-polyfill/dist/browser-polyfill.min'>;
}
