// flow-typed signature: 5107fe7998ce50cc1f66f1046e951f89
// flow-typed version: <<STUB>>/zip-webpack-plugin_v^3.0.0/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zip-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zip-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'zip-webpack-plugin/index' {
  declare module.exports: $Exports<'zip-webpack-plugin'>;
}
declare module 'zip-webpack-plugin/index.js' {
  declare module.exports: $Exports<'zip-webpack-plugin'>;
}
