import mapArrayToEnums from '../../lib/mapArrayToEnums'

module.exports = mapArrayToEnums([
  'REMOVE_TREE_INFOS_FROM_INDEX',
  'REPLACE_TREE_INFO_BY_INDEX',
  'UPDATE_COPY_TARGET',
  'UPDATE_CUT_TARGET',
  'UPDATE_DRAG_TARGET',
  'UPDATE_EDITOR_TARGET',
  'UPDATE_MENU_TARGET',
  'UPDATE_MOUSE_POSITION',
  'UPDATE_SEARCH_KEYWORD',
  'UPDATE_TREES'
])
