// flow-typed signature: bc50f4712b203c6ecbae69dbae04b66d
// flow-typed version: <<STUB>>/@redux-saga/testing-utils_v1.0.1/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@redux-saga/testing-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@redux-saga/testing-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@redux-saga/testing-utils/dist/redux-saga-testing-utils.cjs' {
  declare module.exports: any;
}

declare module '@redux-saga/testing-utils/dist/redux-saga-testing-utils.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@redux-saga/testing-utils/dist/redux-saga-testing-utils.cjs.js' {
  declare module.exports: $Exports<'@redux-saga/testing-utils/dist/redux-saga-testing-utils.cjs'>;
}
declare module '@redux-saga/testing-utils/dist/redux-saga-testing-utils.esm.js' {
  declare module.exports: $Exports<'@redux-saga/testing-utils/dist/redux-saga-testing-utils.esm'>;
}
