export const NO_BOOKMARK_ID_PREFIX = 'NO_BOOKMARK_ID_'
export const DRAG_INDICATOR_ID = 'DRAG_INDICATOR_ID'
export const SEARCH_RESULT_ID = 'SEARCH_RESULT_ID'
export const SEPARATE_THIS_URL = 'http://separatethis.com/'

export enum BOOKMARK_TYPES {
  BOOKMARK,
  DRAG_INDICATOR,
  FOLDER,
  NO_BOOKMARK,
  SEPARATOR,
}
